"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-04 10:07:38.449996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('json_schema', sa.JSON(), nullable=True),
    sa.Column('ai_params', sa.JSON(), nullable=True),
    sa.Column('editor_component', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('default_ai_context_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_ai_context_template_review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ui_layout', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardtype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardtype_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardtype_name'), ['name'], unique=False)

    op.create_table('kgrelation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('a_to_b_addressing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('b_to_a_addressing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recent_dialogues', sa.JSON(), nullable=True),
    sa.Column('recent_event_summaries', sa.JSON(), nullable=True),
    sa.Column('stance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source', 'target', 'kind_en', name='uq_kg_relation_key')
    )
    with op.batch_alter_table('kgrelation', schema=None) as batch_op:
        batch_op.create_index('ix_kg_relation_project_source', ['project_id', 'source'], unique=False)
        batch_op.create_index('ix_kg_relation_project_target', ['project_id', 'target'], unique=False)
        batch_op.create_index(batch_op.f('ix_kgrelation_kind_en'), ['kind_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_kgrelation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kgrelation_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_kgrelation_target'), ['target'], unique=False)

    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_name'), ['name'], unique=True)

    op.create_table('llmconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_protocol', sa.String(), server_default='chat_completions', nullable=False),
    sa.Column('custom_request_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('models_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_limit', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('call_limit', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('used_tokens_input', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_tokens_output', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rpm_limit', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('tpm_limit', sa.Integer(), server_default='-1', nullable=False),
    sa.Column('capability_summary', sa.JSON(), nullable=True),
    sa.Column('recommended_assistant_mode', sa.String(), server_default='auto', nullable=False),
    sa.Column('disable_stream', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('capability_last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llmconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llmconfig_provider'), ['provider'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)

    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_name'), ['name'], unique=True)

    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dsl_version', sa.Integer(), nullable=False),
    sa.Column('is_built_in', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('definition_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keep_run_history', sa.Boolean(), nullable=False),
    sa.Column('triggers_cache', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_name'), ['name'], unique=False)

    op.create_table('bibleupdatereview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_card_id', sa.Integer(), nullable=True),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposal_json', sa.JSON(), nullable=True),
    sa.Column('decisions_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bibleupdatereview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bibleupdatereview_chapter_card_id'), ['chapter_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bibleupdatereview_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bibleupdatereview_status'), ['status'], unique=False)

    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('json_schema', sa.JSON(), nullable=True),
    sa.Column('ai_params', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('card_type_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('ai_context_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_context_template_review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_modified', sa.Boolean(), nullable=False),
    sa.Column('needs_confirmation', sa.Boolean(), nullable=False),
    sa.Column('last_modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['card_type_id'], ['cardtype.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_model_name'), ['model_name'], unique=False)

    op.create_table('foreshadowitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadowitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadowitem_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreshadowitem_type'), ['type'], unique=False)

    op.create_table('workflowrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('max_execution_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflowrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflowrun_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflowrun_status'), ['status'], unique=False)

    op.create_table('nodeexecutionstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('outputs_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkpoint_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflowrun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node_id', name='uq_run_node')
    )
    with op.batch_alter_table('nodeexecutionstate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodeexecutionstate_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodeexecutionstate_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodeexecutionstate_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodeexecutionstate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodeexecutionstate_status'))
        batch_op.drop_index(batch_op.f('ix_nodeexecutionstate_run_id'))
        batch_op.drop_index(batch_op.f('ix_nodeexecutionstate_node_id'))

    op.drop_table('nodeexecutionstate')
    with op.batch_alter_table('workflowrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflowrun_status'))
        batch_op.drop_index(batch_op.f('ix_workflowrun_idempotency_key'))

    op.drop_table('workflowrun')
    with op.batch_alter_table('foreshadowitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadowitem_type'))
        batch_op.drop_index(batch_op.f('ix_foreshadowitem_status'))

    op.drop_table('foreshadowitem')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_model_name'))

    op.drop_table('card')
    with op.batch_alter_table('bibleupdatereview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bibleupdatereview_status'))
        batch_op.drop_index(batch_op.f('ix_bibleupdatereview_project_id'))
        batch_op.drop_index(batch_op.f('ix_bibleupdatereview_chapter_card_id'))

    op.drop_table('bibleupdatereview')
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_name'))

    op.drop_table('workflow')
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_name'))

    op.drop_table('prompt')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    with op.batch_alter_table('llmconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llmconfig_provider'))

    op.drop_table('llmconfig')
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_name'))

    op.drop_table('knowledge')
    with op.batch_alter_table('kgrelation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kgrelation_target'))
        batch_op.drop_index(batch_op.f('ix_kgrelation_source'))
        batch_op.drop_index(batch_op.f('ix_kgrelation_project_id'))
        batch_op.drop_index(batch_op.f('ix_kgrelation_kind_en'))
        batch_op.drop_index('ix_kg_relation_project_target')
        batch_op.drop_index('ix_kg_relation_project_source')

    op.drop_table('kgrelation')
    with op.batch_alter_table('cardtype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardtype_name'))
        batch_op.drop_index(batch_op.f('ix_cardtype_model_name'))

    op.drop_table('cardtype')
    # ### end Alembic commands ###
