"""forge tables

Revision ID: 0002_forge
Revises: 0001_baseline
Create Date: 2026-09-05 09:35:49.789706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0002_forge'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifactprovenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifact_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upstream', sa.JSON(), nullable=True),
    sa.Column('dependency_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('producer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'artifact_kind', 'artifact_key', name='uq_artifact_provenance_key')
    )
    with op.batch_alter_table('artifactprovenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifactprovenance_artifact_key'), ['artifact_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactprovenance_artifact_kind'), ['artifact_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactprovenance_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactprovenance_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactprovenance_stale'), ['stale'], unique=False)

    op.create_table('canonfact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attribute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('valid_from_chapter', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('canon_revision', sa.Integer(), nullable=False),
    sa.Column('support', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonfact', schema=None) as batch_op:
        batch_op.create_index('ix_canon_fact_lookup', ['project_id', 'subject', 'attribute', 'valid_from_chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_attribute'), ['attribute'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_canon_revision'), ['canon_revision'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_chapter_card_id'), ['chapter_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonfact_valid_from_chapter'), ['valid_from_chapter'], unique=False)

    op.create_table('chapterpipelinerun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_card_id', sa.Integer(), nullable=True),
    sa.Column('outline_card_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canon_revision_before', sa.Integer(), nullable=False),
    sa.Column('canon_revision_after', sa.Integer(), nullable=True),
    sa.Column('context_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_manifest', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('style_report', sa.JSON(), nullable=True),
    sa.Column('sync_report', sa.JSON(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapterpipelinerun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapterpipelinerun_chapter_card_id'), ['chapter_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapterpipelinerun_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapterpipelinerun_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapterpipelinerun_status'), ['status'], unique=False)

    op.create_table('projectmanifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('source_manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canon_revision', sa.Integer(), nullable=False),
    sa.Column('outline_revision', sa.Integer(), nullable=False),
    sa.Column('fingerprint_revision', sa.Integer(), nullable=False),
    sa.Column('latest_committed_chapter', sa.Integer(), nullable=False),
    sa.Column('next_allowed_chapter', sa.Integer(), nullable=False),
    sa.Column('context_compiler_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unresolved_errors', sa.JSON(), nullable=True),
    sa.Column('stale_dependency_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_sync_chapter', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projectmanifest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectmanifest_project_id'), ['project_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_projectmanifest_source_project_id'), ['source_project_id'], unique=False)

    op.create_table('referenceexample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('manuscript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_card_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pov_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dominant_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('beat_function', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dialogue_ratio', sa.Float(), nullable=False),
    sa.Column('pacing', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_roles', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('retrieval_terms', sa.JSON(), nullable=True),
    sa.Column('evidence_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'manuscript_id', 'example_id', name='uq_reference_example_key')
    )
    with op.batch_alter_table('referenceexample', schema=None) as batch_op:
        batch_op.create_index('ix_reference_example_project_function', ['project_id', 'beat_function'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_beat_function'), ['beat_function'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_chapter_card_id'), ['chapter_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_evidence_hash'), ['evidence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_manuscript_id'), ['manuscript_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referenceexample_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referenceexample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referenceexample_project_id'))
        batch_op.drop_index(batch_op.f('ix_referenceexample_manuscript_id'))
        batch_op.drop_index(batch_op.f('ix_referenceexample_evidence_hash'))
        batch_op.drop_index(batch_op.f('ix_referenceexample_chapter_number'))
        batch_op.drop_index(batch_op.f('ix_referenceexample_chapter_card_id'))
        batch_op.drop_index(batch_op.f('ix_referenceexample_beat_function'))
        batch_op.drop_index('ix_reference_example_project_function')

    op.drop_table('referenceexample')
    with op.batch_alter_table('projectmanifest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectmanifest_source_project_id'))
        batch_op.drop_index(batch_op.f('ix_projectmanifest_project_id'))

    op.drop_table('projectmanifest')
    with op.batch_alter_table('chapterpipelinerun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapterpipelinerun_status'))
        batch_op.drop_index(batch_op.f('ix_chapterpipelinerun_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapterpipelinerun_chapter_number'))
        batch_op.drop_index(batch_op.f('ix_chapterpipelinerun_chapter_card_id'))

    op.drop_table('chapterpipelinerun')
    with op.batch_alter_table('canonfact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonfact_valid_from_chapter'))
        batch_op.drop_index(batch_op.f('ix_canonfact_superseded_by_id'))
        batch_op.drop_index(batch_op.f('ix_canonfact_subject'))
        batch_op.drop_index(batch_op.f('ix_canonfact_project_id'))
        batch_op.drop_index(batch_op.f('ix_canonfact_fact_id'))
        batch_op.drop_index(batch_op.f('ix_canonfact_chapter_card_id'))
        batch_op.drop_index(batch_op.f('ix_canonfact_canon_revision'))
        batch_op.drop_index(batch_op.f('ix_canonfact_attribute'))
        batch_op.drop_index('ix_canon_fact_lookup')

    op.drop_table('canonfact')
    with op.batch_alter_table('artifactprovenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifactprovenance_stale'))
        batch_op.drop_index(batch_op.f('ix_artifactprovenance_project_id'))
        batch_op.drop_index(batch_op.f('ix_artifactprovenance_card_id'))
        batch_op.drop_index(batch_op.f('ix_artifactprovenance_artifact_kind'))
        batch_op.drop_index(batch_op.f('ix_artifactprovenance_artifact_key'))

    op.drop_table('artifactprovenance')
    # ### end Alembic commands ###
