"""autonomous novel jobs

Revision ID: 0003_autonomous
Revises: 0002_forge
Create Date: 2026-09-05 15:39:17.715410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0003_autonomous'
down_revision: Union[str, None] = '0002_forge'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomousnoveljob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('original_project_id', sa.Integer(), nullable=True),
    sa.Column('llm_config_id', sa.Integer(), nullable=False),
    sa.Column('role_llm_config_ids', sa.JSON(), nullable=True),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('selected_storyline_id', sa.Integer(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('chapters_committed', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_results', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_original_project_id'), ['original_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_source_project_id'), ['source_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_status'), ['status'], unique=False)

    op.create_table('exportartifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exportartifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exportartifact_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exportartifact_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_exportartifact_project_id'), ['project_id'], unique=False)

    op.create_table('jobstageattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recovery_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobstageattempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobstageattempt_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobstageattempt_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobstageattempt_status'), ['status'], unique=False)

    op.create_table('modelinvocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('input_tokens_estimate', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('validation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelinvocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelinvocation_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocation_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocation_stage'), ['stage'], unique=False)

    op.create_table('storylinecandidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('originality_report', sa.JSON(), nullable=True),
    sa.Column('similarity_to_others', sa.JSON(), nullable=True),
    sa.Column('recommended_chapters_min', sa.Integer(), nullable=False),
    sa.Column('recommended_chapters_max', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storylinecandidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storylinecandidate_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storylinecandidate_rejected'), ['rejected'], unique=False)
        batch_op.create_index(batch_op.f('ix_storylinecandidate_source_project_id'), ['source_project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylinecandidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storylinecandidate_source_project_id'))
        batch_op.drop_index(batch_op.f('ix_storylinecandidate_rejected'))
        batch_op.drop_index(batch_op.f('ix_storylinecandidate_job_id'))

    op.drop_table('storylinecandidate')
    with op.batch_alter_table('modelinvocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelinvocation_stage'))
        batch_op.drop_index(batch_op.f('ix_modelinvocation_role'))
        batch_op.drop_index(batch_op.f('ix_modelinvocation_project_id'))
        batch_op.drop_index(batch_op.f('ix_modelinvocation_job_id'))

    op.drop_table('modelinvocation')
    with op.batch_alter_table('jobstageattempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobstageattempt_status'))
        batch_op.drop_index(batch_op.f('ix_jobstageattempt_stage'))
        batch_op.drop_index(batch_op.f('ix_jobstageattempt_job_id'))

    op.drop_table('jobstageattempt')
    with op.batch_alter_table('exportartifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exportartifact_project_id'))
        batch_op.drop_index(batch_op.f('ix_exportartifact_kind'))
        batch_op.drop_index(batch_op.f('ix_exportartifact_job_id'))

    op.drop_table('exportartifact')
    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_status'))
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_stage'))
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_source_project_id'))
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_original_project_id'))
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_idempotency_key'))

    op.drop_table('autonomousnoveljob')
    # ### end Alembic commands ###
