"""lease fencing telemetry budgets

Revision ID: 0004_fencing
Revises: 0003_autonomous
Create Date: 2026-09-05 17:04:08.945184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0004_fencing'
down_revision: Union[str, None] = '0003_autonomous'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelinvocationattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invocation_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config_id', sa.Integer(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_after_seconds', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=True),
    sa.Column('response_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnostic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelinvocationattempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelinvocationattempt_invocation_id'), ['invocation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocationattempt_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocationattempt_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelinvocationattempt_status'), ['status'], unique=False)

    op.create_table('recoveryaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_attempt', sa.Integer(), nullable=False),
    sa.Column('failure_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters_before', sa.JSON(), nullable=True),
    sa.Column('parameters_after', sa.JSON(), nullable=True),
    sa.Column('input_artifact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_artifact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('downstream_invalidations', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recoveryaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recoveryaction_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_recoveryaction_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recoveryaction_stage'), ['stage'], unique=False)

    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_generation', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('budget', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reserved_calls', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reserved_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('repair_calls', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('quality_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('quality_summary', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_autonomousnoveljob_quality_status'), ['quality_status'], unique=False)

    with op.batch_alter_table('exportartifact', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_export_job_kind', ['job_id', 'kind'])

    with op.batch_alter_table('modelinvocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_hash', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('total_attempts', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('selected_attempt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fallback_used', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('storylinecandidate', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_storyline_job_option', ['job_id', 'option_index'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylinecandidate', schema=None) as batch_op:
        batch_op.drop_constraint('uq_storyline_job_option', type_='unique')

    with op.batch_alter_table('modelinvocation', schema=None) as batch_op:
        batch_op.drop_column('finished_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('fallback_used')
        batch_op.drop_column('selected_attempt')
        batch_op.drop_column('total_attempts')
        batch_op.drop_column('prompt_hash')

    with op.batch_alter_table('exportartifact', schema=None) as batch_op:
        batch_op.drop_constraint('uq_export_job_kind', type_='unique')

    with op.batch_alter_table('autonomousnoveljob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autonomousnoveljob_quality_status'))
        batch_op.drop_column('quality_summary')
        batch_op.drop_column('quality_status')
        batch_op.drop_column('repair_calls')
        batch_op.drop_column('reserved_tokens')
        batch_op.drop_column('reserved_calls')
        batch_op.drop_column('budget')
        batch_op.drop_column('lease_generation')

    with op.batch_alter_table('recoveryaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recoveryaction_stage'))
        batch_op.drop_index(batch_op.f('ix_recoveryaction_job_id'))
        batch_op.drop_index(batch_op.f('ix_recoveryaction_action'))

    op.drop_table('recoveryaction')
    with op.batch_alter_table('modelinvocationattempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelinvocationattempt_status'))
        batch_op.drop_index(batch_op.f('ix_modelinvocationattempt_role'))
        batch_op.drop_index(batch_op.f('ix_modelinvocationattempt_job_id'))
        batch_op.drop_index(batch_op.f('ix_modelinvocationattempt_invocation_id'))

    op.drop_table('modelinvocationattempt')
    # ### end Alembic commands ###
